export enum ESizeFormat {
  G = 'g',
  ML = 'ml',
  UD = 'ud',
  // M = 'm',
  // SM = 'sm',
  // MM = 'mm',
}

export enum EUdSizeFormat {
  G = 'g',
  ML = 'ml',
}

export enum ESellerizeFormat {
  KG = 'kg',
  G = 'g',
  L = 'l',
  ML = 'ml',
  UD = 'ud',
  DOCENA = 'docena',
  M = 'm',
  SM = 'sm',
  MM = 'mm',
}

export enum EPackaging {
  BANDEJA = 'Bandeja',
  BENJAMIN = 'Benjamín',
  BOL = 'Bol',
  BOLSA = 'Bolsa',
  BOTE = 'Bote',
  BOTELLA = 'Botella',
  BOTELLIN = 'Botellín',
  BRICK = 'Brick',
  CAJA = 'Caja',
  CARTON = 'Cartón',
  FRASCO = 'Frasco',
  GARRAFA = 'Garrafa',
  GRANEL = 'Granel',
  LATA = 'Lata',
  MALLA = 'Malla',
  MANOJO = 'Manojo',
  PIEZA_MEDIO = '1/2 Pieza',
  PIEZA_CUARTO = '1/4 Pieza',
  PAQUETE = 'Paquete',
  PASTILLA = 'Pastilla',
  PACK_2 = 'Pack-2',
  PACK_3 = 'Pack-3',
  PACK_4 = 'Pack-4',
  PACK_5 = 'Pack-5',
  PACK_6 = 'Pack-6',
  PACK_8 = 'Pack-8',
  PACK_9 = 'Pack-9',
  PACK_10 = 'Pack-10',
  PACK_12 = 'Pack-12',
  PACK_16 = 'Pack-16',
  PIEZA = 'Pieza',
  SACO = 'Saco',
  SOBRE = 'Sobre',
  SPRAY = 'Spray',
  TABLETA = 'Tableta',
  TARRO = 'Tarro',
  TARRINA = 'Tarrina',
  TARRITO = 'Tarrito',
  TUBO = 'Tubo',
  VASO = 'Vaso',
}
